BulkTransferException: add stack traces
Do not hide error message behind BulkTransferException. Instead, for
each unique message, print a full stack trace including its cause(s).